- name: conditions in yaml
  hosts: localhost
  vars:
    name1: devops
  tasks:
  - name: checking user
    ansible.builtin.command: id roboshop
    register: output
  - name: validating
    ansible.builtin.debug:
      msg: "output" 
  - name: creating user roboshop
    ansible.builtin.user:
    name: roboshop
    when: output.rc -ne 0    
