- name: conditions in yaml
  hosts: localhost
  tasks:
  - name: checking user
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: True
  - name: validating
    ansible.builtin.debug:
      msg: output.rc 
  - name: creating user roboshop
    become: yes
    ansible.builtin.user:
      name: roboshop
    when: output.rc != 0    
