- name: conditions in yaml
  hosts: localhost
  vars:
    name1: devops
  tasks:
  - name: checking user
    ansible.builtin.command: id roboshop
    register: output
  - name: validating
    ansible.builtin.debug:
      msg: "output" 
