- name: checking directory exits or not
  hosts: localhost
  become: yes
  tasks:
  - name: checking directory exists or not
    ansible.builtin.stat:
      path: "/home/centos/roboshell1/mouli"
    register: output
  - name: directory exists
    ansible.builtin.debug:
      msg: "mouli directory exists"
    when: output.stat.exists
  - name: directory exists
    ansible.builtin.command: mkdir mouli
    register: rakesh
    when: not output.stat.exists  

     