- name: loops in ansible
  hosts: nginx
  become: yes
  tasks:
  - name: installing nginx and postfix
    ansible.builtin.yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'absent' }
    - { name: 'ansible', state: 'absent'}