- name: installing shipping
  hosts: shipping
  become: yes
  tasks: 
  - name: installing maven
    ansible.builtin.yum:
      name: maven
      state: installed
  - name: checking user roboshop
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: printing output
    ansible.builtin.debug:
      msg: "{{output.rc}}"  
           
  - name: adding user roboshop
    ansible.builtin.user:
      name: roboshop 
    when: output.rc !=0     