- name: 6 types of vars
  hosts: nginx
  # vars_prompt:

  #   - name: name1
  #     prompt: What is your username?
  #     private: true

  # vars:
  #   name1: play-vars-rakesh
  #   house: gotlur
  # vars_files:
  #   - variables.yaml  
  tasks:
  - name: printing the vars
    # vars:
    #   name1: task-vars-dubbu
    #   house: sweden
    ansible.builtin.debug:
      msg: "welcome to {{name1}},he lives in {{house}} and he knows {{name1}} "  
#1. command line
#2.task level
#3.vars_files
#4.prompt
#5.play-level
#6.inventory

