- name: 6 types of vars
  hosts: nginx
  vars_prompt:

    - name: name
      prompt: What is your username?
      private: false

  vars:
    name: play-vars-rakesh
    house: gotlur
  vars_files:
    - variables.yaml  
  tasks:
  - name: printing the vars
    vars:
      name: task-vars-dubbu
      house: sweden
    ansible.builtin.debug:
      msg: "welcome to {{name}},he lives in {{house}} and he knows {{name}}"  

