- name: installing web
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: Start service nginx, if not started
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes    
  - name: Delete content & directory
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html  
  
  
  - name: Create a directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
      
     
  - name: Downloading frontend content
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp   
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes   
  - name: copying roboshop.conf
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf
  - name: Restart service nginx, in all cases
    ansible.builtin.service:
      name: nginx
      state: restarted     
  


