- name: installing web
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: enabling and starting nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes    
  - name: Delete content & directory
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/*  

